name: Deploy Tool to NuGet

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    name: "Build Project"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    env:
      MajorVersion: 0
      MinorVersion: 5
    steps:
    - uses: actions/checkout@v2

    # Get a short-lived NuGet API key
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
        
    - name: Get current date
      id: version
      run: echo "::set-output name=date::$(date +'%Y%m.%d')"

    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      run: echo "Branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      run: echo "Branch=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Set Version Prefix
      env:
        VERPREF: ${{ format('{0}.{1}.{2}{3}', env.MajorVersion, env.MinorVersion, steps.date.outputs.date, github.run_number) }}
      run: echo "VersionPrefix=$(echo ${VERPREF})" >> $GITHUB_ENV
    
    - name: Setup .NET 8.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.x

    - name: Setup .NET 10.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.x

    - name: Build Project
      run: dotnet pack ./src/HaveIBeenPwned.PwnedPasswords.Downloader/HaveIBeenPwned.PwnedPasswords.Downloader.csproj --configuration Release
    
    # Push the package
    - name: NuGet push
      run: dotnet nuget push  ./src/HaveIBeenPwned.PwnedPasswords.Downloader/nupkg/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
